littlehorse-enterprises/littlehorse

examples/wf-versions/README.md

adds a bit more color to wf-versions-example docs

MINOR: add to example docs

---

e2e-tests/src/main/java/io/littlehorse/tests/WorkflowLogicTest.java
e2e-tests/src/main/java/io/littlehorse/tests/cases/workflow/AXConditionalWhileLogic.java
examples/basic/src/main/java/io/littlehorse/examples/BasicExample.java
sdk-java/src/main/java/io/littlehorse/sdk/wfsdk/internal/ThreadBuilderImpl.java
sdk-java/src/test/java/io/littlehorse/sdk/wfsdk/internal/ThreadBuilderImplTest.java

- missing edge on while loop conditionals
- ensure no outgoing edge on EXIT nodes
Also fixes unit tests that weren't actually checking anything.

Fixes minor SDK bugs:

---

e2e-tests/src/main/java/io/littlehorse/tests/cases/lifecycle/AFTaskAndUserTaskSearch.java
e2e-tests/src/main/java/io/littlehorse/tests/cases/workflow/AZUserTasksBasic.java
e2e-tests/src/main/java/io/littlehorse/tests/cases/workflow/BEUserTasksCancel.java
examples/user-tasks/src/main/java/io/littlehorse/examples/UserTasksExample.java
sdk-java/src/main/java/io/littlehorse/sdk/wfsdk/ThreadBuilder.java
sdk-java/src/main/java/io/littlehorse/sdk/wfsdk/internal/ThreadBuilderImpl.java

* Renames user task methods in Java

0.2.0 Finishing Touches

---

server/src/main/java/io/littlehorse/server/streams/topology/core/processors/CommandProcessor.java

Now log.debug for user errors during command processing. Reserve log.error for actual errors.

MINOR: Command Processor Log Level

---

server/src/main/java/io/littlehorse/server/streams/BackendInternalComms.java

consistency for not found messages
Jira Ticket: https://littlehorse.atlassian.net/browse/LH-114

consistency for not found messages

---

docs/CLIENT_CONFIGURATIONS.md
go.mod
local-dev/configs/mtls.config
local-dev/configs/oauth.config
local-dev/configs/tls.config
sdk-go/common/lh_config.go
sdk-java/src/main/java/io/littlehorse/sdk/common/config/LHConfig.java
sdk-java/src/test/java/io/littlehorse/sdk/common/config/LHClientConfigTest.java
sdk-python/littlehorse/config.py
sdk-python/tests/test_config.py

* Includes python, go and java
* Update config examples

Add LHC_API_PROTOCOL to SDKs

---

lhctl/cmd/version.go
server/src/main/java/io/littlehorse/server/KafkaStreamsServerImpl.java

TODO: this should be automated.

updates lhctl version to the next upcoming release.

---

server/src/test/java/e2e/TaskDefIdempotencyTest.java

Adds end to end test to verify integrity of metadata processor

Metadata Processor Integrity E2E Test

---

sdk-java/src/main/java/io/littlehorse/sdk/common/auth/TenantMetadataProvider.java
sdk-java/src/main/java/io/littlehorse/sdk/common/config/LHConfig.java
server/src/main/java/io/littlehorse/server/auth/InternalAuthorizer.java

This PR add a new class (TenantMetadataProvider) that will intercept grpc request on the java client side and add metadata for the client tenant
https://github.com/littlehorse-enterprises/littlehorse/issues/578

Enable SDK Java clients sending tenantId header

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/enhancement.yml
.github/ISSUE_TEMPLATE/tech-debt.yml
.github/ISSUE_TEMPLATE/user-story.yml

changes user story template to not have a task list

feature: changes user story template to not have a task list

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/enhancement.yml
.github/ISSUE_TEMPLATE/tech-debt.yml
.github/ISSUE_TEMPLATE/user-story.yml

Using drop-down for components

Fix Issue Templates

---

.github/actions/publish-image/action.yml
docker/standalone/dashboard-entrypoint.sh
sdk-go/wflib/wf_lib_internal_test.go

This PR fixes an issue with the standalone image that prevents the user to access the dashboard.
As an extra this also enables the platforms `linux/amd64` and `linux/arm641 and some minor linter issues.

Fix standalone image

---

sdk-go/wflib/wf_lib_internal_test.go
sdk-go/wflib/wf_lib_public.go
sdk-python/littlehorse/workflow.py
sdk-python/tests/test_workflow.py

adds thread retention policy and workflow retention policy to go sdk

---

schemas/common_wfspec.proto
sdk-go/wflib/wf_lib_internal_test.go
sdk-python/tests/test_workflow.py
server/src/main/java/io/littlehorse/common/model/getable/core/wfrun/WfRunModel.java

- includes some indentations fixes
- debug instead of info

chore: change log level for completed wf runs

---

sdk-python/littlehorse/config.py
sdk-python/littlehorse/worker.py
sdk-python/tests/test_config.py

Infinite max_pings_without_data

fix: python grpc configurations

---

lhctl/cmd/version.go
server/src/main/java/io/littlehorse/server/KafkaStreamsServerImpl.java

This REALLY needs to be automated. I messed it up on the last release, oops.

updates to 0.7.2

---

sdk-java/src/main/java/io/littlehorse/sdk/common/LHLibUtil.java
sdk-java/src/test/java/io/littlehorse/sdk/common/LHLibUtilTest.java
server/src/main/java/io/littlehorse/common/model/getable/global/wfspec/thread/ThreadRetentionPolicyModel.java

- Ensure that threadruns with retention policy of zero seconds are immediately deleted
- Fixes the LHLibUtil.wfRunIdToString() method.

Small fixes:

---

server/src/main/java/io/littlehorse/common/util/LHUtil.java
server/src/main/java/io/littlehorse/server/KafkaStreamsServerImpl.java
server/src/main/java/io/littlehorse/server/streams/topology/core/processors/CommandProcessor.java

MINOR: don't log stacktrace for 400-like errors

---

.pre-commit-config.yaml
sdk-js/package-lock.json

The current pre-commit fails due missing dependencies on sdk-js
Related to #686

fix(sdk-js): add pre-commit npm install

---

server/src/main/java/io/littlehorse/common/model/getable/global/wfspec/node/FailureDefModel.java
server/src/main/java/io/littlehorse/common/model/getable/global/wfspec/node/NodeModel.java
server/src/test/java/io/littlehorse/TestUtil.java
server/src/test/java/io/littlehorse/common/model/getable/global/wfspec/node/NodeModelTest.java
server/src/test/java/io/littlehorse/common/model/getable/global/wfspec/node/subnode/ExitNodeModelTest.java

514 validate names for errorexception

---

dashboard/apps/web/components/Drawer/internals/drawerInternals.ts

Build failing due linter error. It doesn't like semicolons ;

fix(linter): extra semicolon

---

dashboard-new/src/app/(authenticated)/wfRun/[...ids]/components/Details.tsx
dashboard-new/src/app/(authenticated)/wfRun/[...ids]/getWfRun.ts
dashboard-new/src/app/(authenticated)/wfRun/[...ids]/page.tsx
dashboard-new/src/app/(authenticated)/wfSpec/[...props]/components/Diagram.tsx
dashboard-new/src/app/(authenticated)/wfSpec/[...props]/components/NodeTypes/StartMultipleThreads.tsx
dashboard-new/src/app/(authenticated)/wfSpec/[...props]/components/NodeTypes/StartThread.tsx
dashboard-new/src/app/(authenticated)/wfSpec/[...props]/components/NodeTypes/StatusPin.tsx
dashboard-new/src/app/(authenticated)/wfSpec/[...props]/components/NodeTypes/Task.tsx
dashboard-new/src/app/(authenticated)/wfSpec/[...props]/components/NodeTypes/TaskDetails.tsx
dashboard-new/src/app/(authenticated)/wfSpec/[...props]/components/NodeTypes/UserTask.tsx
dashboard-new/src/app/(authenticated)/wfSpec/[...props]/components/NodeTypes/WaitForThreads.tsx
dashboard-new/src/app/(authenticated)/wfSpec/[...props]/components/NodeTypes/index.ts
dashboard-new/src/app/(authenticated)/wfSpec/[...props]/components/ThreadPanel.tsx
dashboard-new/src/app/(authenticated)/wfSpec/[...props]/components/WfRuns.tsx
dashboard-new/src/app/(authenticated)/wfSpec/[...props]/hooks/useThread.tsx
dashboard-new/src/app/api/auth/signin/page.tsx
dashboard-new/src/app/utils/index.ts
dashboard-new/src/app/utils/wfRun.test.ts
dashboard-new/src/app/utils/wfRun.ts

This PR enables thread nodes, this includes:
- StartThread
- StartMultipleThreads
- WaitForThreads

feat(dashboard): handle threads

---

server/src/main/java/io/littlehorse/server/monitoring/metrics/ServerFilterRules.java

- Edits the metrics filter rules to add some kafka consumer metrics, including lag
- Adds some more rebalance metrics

More Metrics

---

dashboard/src/app/(authenticated)/(diagram)/components/NodeTypes/Task/TaskDetails.tsx
dashboard/src/app/(authenticated)/(diagram)/components/ThreadPanel.tsx

Fixes missing button hightlight on thread selector

fix(dashboard): fixes thread selector highlight

---

server/src/main/java/io/littlehorse/common/model/getable/core/usertaskrun/UserTaskRunModel.java
server/src/test/java/io/littlehorse/common/model/getable/core/usertaskrun/UserTaskRunModelTest.java

UserTaskRunModel did not have enough indexes

Fix: issue 805

---

server/src/main/java/io/littlehorse/server/KafkaStreamsServerImpl.java

MINOR: logs when Streams is done closing down

---

server/src/main/java/io/littlehorse/common/model/getable/global/acl/PrincipalModel.java
server/src/main/java/io/littlehorse/server/streams/storeinternals/ReadOnlyMetadataManager.java
server/src/main/java/io/littlehorse/server/streams/topology/core/WfService.java

- Add proper index on the PrincipalModel for isAdmin
- Fix the tag scan implementation in WfService#adminPrincipalIds()

fix(server): Correctly detect whether admin principals exist

---

dashboard/src/app/(authenticated)/(diagram)/components/NodeTypes/Task/Task.tsx
dashboard/src/app/(authenticated)/(diagram)/components/NodeTypes/Task/TaskDetails.tsx
dashboard/src/app/(authenticated)/taskDef/[name]/components/TaskDef.tsx

feat(dashboard): taskRun actual values

---

dashboard/src/app/(authenticated)/(diagram)/components/Diagram.tsx
dashboard/src/app/(authenticated)/taskDef/[name]/components/TaskDef.tsx

feat(dashboard): highlight taskRun on diagram

---

dashboard/src/app/(authenticated)/(diagram)/components/ThreadPanel.tsx
dashboard/src/app/(authenticated)/(diagram)/hooks/useReplaceQueryValue.tsx
dashboard/src/app/(authenticated)/(diagram)/wfRun/[...ids]/components/Variables.tsx
dashboard/src/app/(authenticated)/(diagram)/wfRun/[...ids]/components/WfRun.tsx
dashboard/src/app/(authenticated)/(diagram)/wfRun/[...ids]/getWfRun.ts
dashboard/src/app/(authenticated)/(diagram)/wfRun/[...ids]/page.tsx

feat(dashboard): `WfSpec` var values are shown for current `ThreadRun`

---

lhctl/cmd/wf_run.go
server/src/main/java/io/littlehorse/common/model/getable/core/wfrun/WfRunModel.java
server/src/main/java/io/littlehorse/server/streams/lhinternalscan/publicrequests/SearchWfRunRequestModel.java
server/src/main/java/io/littlehorse/server/streams/stores/ReadOnlyBaseStoreImpl.java
server/src/test/java/io/littlehorse/storeinternals/GetableManagerTest.java

feat(server): support search wfrun by name and version

---

dashboard/package-lock.json
dashboard/package.json
dashboard/src/app/(authenticated)/(diagram)/wfSpec/[...props]/actions/searchVariables.ts
dashboard/src/app/(authenticated)/(diagram)/wfSpec/[...props]/actions/searchWfRun.ts
dashboard/src/app/(authenticated)/(diagram)/wfSpec/[...props]/components/SearchVariableDialog.tsx
dashboard/src/app/(authenticated)/(diagram)/wfSpec/[...props]/components/WfRuns.tsx
dashboard/src/app/(authenticated)/(diagram)/wfSpec/[...props]/components/WfRunsHeader.tsx
dashboard/src/app/(authenticated)/(diagram)/wfSpec/[...props]/components/WfSpec.tsx
dashboard/src/components/ui/button.tsx
dashboard/src/components/ui/dialog.tsx
dashboard/src/components/ui/input.tsx
dashboard/src/components/ui/select.tsx

feat(dashboard): search for `wfRuns` by variable `name` & `value`

---

dashboard/src/app/(authenticated)/(diagram)/components/EdgeTypes/Default.tsx
dashboard/src/app/(authenticated)/(diagram)/components/EdgeTypes/EdgeDetails.tsx
dashboard/src/app/(authenticated)/(diagram)/components/Layouter.tsx
dashboard/src/app/(authenticated)/(diagram)/components/Modals/Edge.tsx
dashboard/src/app/(authenticated)/(diagram)/components/Modals/index.ts
dashboard/src/app/(authenticated)/(diagram)/context/ModalContext.tsx
dashboard/src/app/(authenticated)/(diagram)/layout.tsx
dashboard/src/app/(authenticated)/(diagram)/wfRun/[...ids]/components/WfRun.tsx

feat(dashboard): edge modal to display details (mutations, errors, etc.)

---

server/src/main/java/io/littlehorse/server/KafkaStreamsServerImpl.java
server/src/main/java/io/littlehorse/server/streams/BackendInternalComms.java

fix(server): Fixes noisy exceptions on getObject internal request failures

---

dashboard/src/app/(authenticated)/(diagram)/components/Modals/TaskRun.tsx
dashboard/src/components/ui/dialog.tsx

fix(dashboard): large text support on modals

---

sdk-java/src/main/java/io/littlehorse/sdk/common/config/LHConfig.java

Some clients require to send async requests to the server this is helpful for high throughput use cases, for instance, executing `rpc RunWf()` high number of requests per second.

feat(sdk-java): Support future stubs for async API requests

---

.github/workflows/release.yml
cliff.toml

This PR adds lhctl binaries to the release page and generates release notes for every new release.
Supersedes #913

ci(lhctl): release lhctl binaries and generate release notes

---

dashboard/src/app/(authenticated)/(diagram)/components/Modals/TaskRun.tsx
dashboard/src/components/ui/dialog.tsx

fix(dashboard): max height for `Dialog`

---

dashboard/src/app/(authenticated)/(diagram)/components/NodeTypes/UserTask/UserTask.tsx
dashboard/src/app/(authenticated)/(diagram)/wfSpec/[...props]/components/WfRuns.tsx
dashboard/src/app/(authenticated)/components/Search.tsx
dashboard/src/app/(authenticated)/components/SearchHeader.tsx
dashboard/src/app/(authenticated)/externalEventDef/[name]/components/ExternalEventDef.tsx
dashboard/src/app/(authenticated)/taskDef/[name]/components/TaskDef.tsx
dashboard/src/app/(authenticated)/userTaskDef/[...props]/components/UserTaskDef.tsx

fix(dashboard): icons correctly apply colors

---

sdk-dotnet/CONTRIBUTING.md

- Add instructions to install different dotnet versions in Ubuntu and pick one to build a project

docs(contributing): Add Contributing File for Donet-SDK project

---

.gitignore
sdk-dotnet/Examples/BasicExample/BasicExample.csproj
sdk-dotnet/Examples/BasicExample/MyWorker.cs
sdk-dotnet/Examples/BasicExample/Program.cs
sdk-dotnet/LittleHorse.Sdk.Tests/LittleHorse.Sdk.Tests.csproj
sdk-dotnet/LittleHorse.Sdk.Tests/UnitTest1.cs
sdk-dotnet/LittleHorse.Sdk/CONTRIBUTING.md
sdk-dotnet/LittleHorse.Sdk/Exceptions/LHAuthorizationServerException.cs
sdk-dotnet/LittleHorse.Sdk/Exceptions/LHInputVarSubstitutionException.cs
sdk-dotnet/LittleHorse.Sdk/Exceptions/LHMisconfigurationException.cs
sdk-dotnet/LittleHorse.Sdk/Exceptions/LHSerdeException.cs
sdk-dotnet/LittleHorse.Sdk/Exceptions/LHTaskSchemaMismatchException.cs
sdk-dotnet/LittleHorse.Sdk/Helper/LHMappingHelper.cs
sdk-dotnet/LittleHorse.Sdk/Helper/LHWorkerHelper.cs
sdk-dotnet/LittleHorse.Sdk/LHConfig.cs
sdk-dotnet/LittleHorse.Sdk/LHServerConnection.cs
sdk-dotnet/LittleHorse.Sdk/LHServerConnectionManager.cs
sdk-dotnet/LittleHorse.Sdk/LHTaskMethodAttribute.cs
sdk-dotnet/LittleHorse.Sdk/LHTaskSignature.cs
sdk-dotnet/LittleHorse.Sdk/LHTaskWorker.cs
sdk-dotnet/LittleHorse.Sdk/LHWorkerContext.cs
sdk-dotnet/LittleHorse.Sdk/LHWorkerOptions.cs
sdk-dotnet/LittleHorse.Sdk/LittleHorse.Sdk.csproj
sdk-dotnet/LittleHorse.Sdk/VariableMapping.cs
sdk-dotnet/README.md

- Refactor Dotnet SDK code to avoid using much complexity using builders and interfaces
- Added some dotnet files to gitignore
- Fixed the dotnet basic example

Refactor Dotnet SDK

---

canary/build.gradle
server/build.gradle

Solves a vulnerability problem related to javalin dependency

chore(lh-server): Updates javalin version

---

.github/workflows/tests.yml
.pre-commit-config.yaml
sdk-python/poetry.lock
sdk-python/pyproject.toml

Expanding this PR https://github.com/littlehorse-enterprises/littlehorse/pull/1020

fix(security): upgrade sdk-python dependencies

---

dashboard/src/app/(authenticated)/(diagram)/components/Modals/ExternalEvent.tsx
dashboard/src/app/(authenticated)/(diagram)/components/Modals/TaskRun.tsx
dashboard/src/app/(authenticated)/(diagram)/components/Modals/WorkflowEvent.tsx

feat(dashboard): copy ids to clipboard in `WfRun`

---

dashboard/src/app/(authenticated)/(diagram)/components/Modals/ExternalEvent.tsx
dashboard/src/app/(authenticated)/(diagram)/components/Modals/TaskRun.tsx
dashboard/src/app/(authenticated)/(diagram)/components/Modals/WorkflowEvent.tsx
dashboard/src/app/(authenticated)/(diagram)/wfSpec/[...props]/components/WfRuns.tsx
dashboard/src/app/constants.ts

resolves #1069
- added support for all-time date range of `WfRuns`.

feat(dashboard): support unlimited time

---

.gitignore
sdk-dotnet/Examples/MaskedFieldsExample/MaskedFieldsExample.csproj
sdk-dotnet/Examples/MaskedFieldsExample/Program.cs
sdk-dotnet/Examples/MaskedFieldsExample/README.md
sdk-dotnet/Examples/MaskedFieldsExample/Worker.cs

- Add new project with masking data example
- Add readme file

docs(dotnet-sdk): add dotnet example to mask input and output fields

---

server/src/main/java/io/littlehorse/server/streams/topology/core/WfService.java

Adjusts exception message to be more descriptive and use gRPC Status Code UNAVAILABLE when Anonymous Principal not found in store.

fix(server): Update exception when anonymous principal not found in store

---

sdk-dotnet/LittleHorse.Sdk.Tests/Helper/LHMappingHelperTest.cs
sdk-dotnet/LittleHorse.Sdk.Tests/LHTaskSignatureTest.cs
sdk-dotnet/LittleHorse.Sdk.Tests/TestClasses.cs
sdk-dotnet/LittleHorse.Sdk.Tests/Utils/JsonHandlerTest.cs
sdk-dotnet/LittleHorse.Sdk/Helper/LHMappingHelper.cs
sdk-dotnet/LittleHorse.Sdk/Utils/JsonHandler.cs
sdk-dotnet/LittleHorse.Sdk/Worker/Internal/LHServerConnectionManager.cs
sdk-dotnet/LittleHorse.Sdk/Worker/LHTaskSignature.cs
sdk-dotnet/LittleHorse.Sdk/Worker/VariableMapping.cs

- Fix deserialization json strings in Task Worker 
- Fix mapping helper
- Add unit tests

fix(dotnet-sdk): fix variable types mapping 

---

dashboard/src/app/[tenantId]/components/tables/WfSpecTable.tsx

- we missed one href
- I double checked all the others and good to go

fix(dashboard): use `tenantId` in href for `WfSpec`s

---

dashboard/src/app/[tenantId]/(diagram)/wfSpec/[...props]/components/WfRunsHeader.tsx
dashboard/src/app/constants.ts

resolves #1179 
- Changed wording to "All time"

refactor(dashboard): professional all time display

---

docs/docs/05-developer-guide/08-wfspec-development/08-user-tasks.md
sdk-python/examples/user_tasks/README.md
sdk-python/examples/user_tasks/user_tasks.py
sdk-python/littlehorse/workflow.py

- Fix args param which created a tuple of tuple not allowed to process it
- Add user task example

fix(python-sdk): fix args in schedule reminder method

---

sdk-dotnet/LittleHorse.Sdk.Tests/Helper/LHMappingHelperTest.cs
sdk-dotnet/LittleHorse.Sdk.Tests/Worker/VariableMappingTest.cs
sdk-dotnet/LittleHorse.Sdk/Helper/LHMappingHelper.cs

- Fix mapping from input dictionary dotnet type into json_obj LH Type
- Modify and add unit tests

fix(sdk-dotnet): solve mapping dictionary as input in task method

---

server/src/main/java/io/littlehorse/server/streams/ServerTopology.java
server/src/main/java/io/littlehorse/server/streams/taskqueue/OneTaskQueue.java

Removes unused repartition store and processor.

chore(server): drop core repartition processor and stores

---

dashboard/src/app/[tenantId]/(diagram)/components/EdgeTypes/extractEdges.ts
dashboard/src/app/[tenantId]/(diagram)/components/Modals/NodeRun/AccordionContent.ts
dashboard/src/app/[tenantId]/(diagram)/components/Modals/NodeRun/NodeRun.tsx
dashboard/src/app/[tenantId]/(diagram)/components/Modals/NodeRun/WaitForConditionDefDetail.tsx
dashboard/src/app/[tenantId]/(diagram)/components/NodeTypes/Task/TaskDetails.tsx
dashboard/src/app/[tenantId]/(diagram)/components/NodeTypes/WaitForCondition/Condition.tsx
dashboard/src/app/[tenantId]/(diagram)/components/NodeTypes/WaitForCondition/WaitForCondition.tsx
dashboard/src/app/[tenantId]/(diagram)/components/NodeTypes/WaitForCondition/getWaitForCondition.ts
dashboard/src/app/[tenantId]/(diagram)/components/NodeTypes/WaitForCondition/index.ts
dashboard/src/app/[tenantId]/(diagram)/components/NodeTypes/extractNodes.ts
dashboard/src/app/[tenantId]/(diagram)/components/NodeTypes/index.ts
dashboard/src/app/[tenantId]/components/OverflowText.tsx
dashboard/src/app/utils/comparatorUtils.ts

resolves #1048
https://github.com/user-attachments/assets/7f0c736d-dbec-45a7-8552-bdfc462368de

feat(dashboard): wait_for_condition implementation

---

test-utils/src/main/java/io/littlehorse/test/internal/step/VerifyTaskRunOutputsStep.java

Co-authored-by: Saul Piña <saul@littlehorse.io>

refactor(test-utils): adds support for all variable types in node output

---

.github/workflows/tests.yml

- Multiple GoLang Versions (1.21, 1.22, 1.23)

build(ci): test multiple go sdk versions

---

sdk-java/src/main/java/io/littlehorse/sdk/common/config/LHConfig.java
sdk-java/src/test/java/io/littlehorse/sdk/common/config/LHClientConfigTest.java

- Uses an enum to define all the settings and then it exports them as a set with configNames()

fix(sdk-java): adds missing configs to sdk java

---

sdk-python/littlehorse/workflow.py
sdk-python/tests/test_workflow.py
test-utils-container/src/main/java/io/littlehorse/container/LittleHorseCluster.java

feat(test-utils): add network to lh test container

---

dashboard/src/app/(authenticated)/[tenantId]/taskDef/[name]/components/TaskDef.tsx
dashboard/src/app/actions/getWfSpecsByTaskDef.tsx

resolves #1239
- Added infinite query for WfSpec search
- Restyled structure to be side by side
- As we've discussed, side by side is better due to the potential large lists that one would have to scroll past.

feat(dashboard): restyle wfspecs usage display

---

lhctl/internal/user_task_run.go
sdk-go/littlehorse/lh_variables.go
sdk-go/littlehorse/lh_variables_test.go

fix(lhctl): Replace `\n` removal with `TrimSpace` in UserTaskRun parsing

---

dashboard/src/app/(authenticated)/[tenantId]/components/VersionTag.tsx
dashboard/src/app/(authenticated)/[tenantId]/components/tables/ExternalEventDefTable.tsx
dashboard/src/app/(authenticated)/[tenantId]/components/tables/TaskDefTable.tsx
dashboard/src/app/(authenticated)/[tenantId]/components/tables/UserTaskDefTable.tsx
dashboard/src/app/(authenticated)/[tenantId]/components/tables/WfSpecTable.tsx
dashboard/src/app/(authenticated)/[tenantId]/components/tables/WorkflowEventDefTable.tsx

resolves #1297 
- Uses the `SelectionLink.tsx` component across all `Search` tabs
https://github.com/user-attachments/assets/a01762b0-cd47-47fd-a29c-d62072a56c4b

feat(dashboard): use SelectionLink across all search results

---

dashboard/src/middleware.ts

resolves [#1341](https://github.com/littlehorse-enterprises/littlehorse/issues/1341)
- Checks token validity against Keycloak's OIDC userinfo endpoint
- Same fix that User Task Bridge frontend uses.

fix(dashboard): sign in if accessToken invalid

---

sdk-java/build.gradle
sdk-java/src/main/java/io/littlehorse/sdk/worker/LHTaskWorker.java

chore(sdk-java): Remove awaitility dependency

---

dashboard/src/app/(authenticated)/[tenantId]/components/Principal.tsx
dashboard/src/app/api/auth/[...nextauth]/authOptions.ts

resolves [#1295](https://github.com/littlehorse-enterprises/littlehorse/issues/1295)
- Removed conditional render of sign out button, as discussed with @hazimoarafa
- Added next-auth sign out handling with keycloak
https://github.com/user-attachments/assets/ffcc2f18-4c22-4e8c-8c7d-d1c27a082420

fix(dashboard): fix sign out

---

.github/workflows/tests.yml
dashboard/package-lock.json
dashboard/package.json
dashboard/src/app/(authenticated)/[tenantId]/(diagram)/wfSpec/[...props]/components/WfRuns.tsx
package-lock.json

- Add better identification for data caching, to prevent irrelevant data population on separate pages

fix(dashboard): revalidate cache with proper keys

---

dashboard/src/app/(authenticated)/[tenantId]/(diagram)/components/EdgeTypes/extractEdges.ts

resolves [#1444](https://github.com/littlehorse-enterprises/littlehorse/issues/1444)

fix(dashboard): quotes around raw string values

---

dashboard/src/app/(authenticated)/[tenantId]/(diagram)/components/ThreadPanel.tsx

resolves #1445
https://github.com/user-attachments/assets/c95a1b41-c77b-42c9-a7c8-b066276a5c2f

fix(dashboard): scrollable thread panels

---

sdk-python/examples/basic/example_basic.py
sdk-python/littlehorse/workflow.py

feat(sdk-python): Add lambdas support for `ThreadInitializer`s

---

.github/workflows/tests.yml
sdk-js/package-lock.json
sdk-python/examples/child_threads/example_child_thread.py
sdk-python/littlehorse/worker.py
sdk-python/littlehorse/workflow.py
sdk-python/tests/test_config.py
sdk-python/tests/test_utils.py
sdk-python/tests/test_workflow.py

It includes:
- Fix signal.SIGHUP
- Fix tests on windows
- Update pipeline
- Format python code
Drawbacks:
- 4 extra checks in the pipeline

fix(sdk-python): windows compatible

---

README.md

Updates Slack URL to new Launchpass URL scheme

chore(README): Update Slack URL

---

proposals/000-struct-and-structdef.md
proposals/README.md

Proposal for the ticket #880 .

doc(arc): add struct and structdef proposal

---

sdk-dotnet/Examples/UserTasksExample/Program.cs
sdk-dotnet/LittleHorse.Sdk.Tests/Workflow/Spec/WorkflowIfStatementTest.cs
sdk-dotnet/LittleHorse.Sdk/Workflow/Spec/WorkflowIfStatement.cs
sdk-dotnet/LittleHorse.Sdk/Workflow/Spec/WorkflowThread.cs

- Fix edge case
- Refactor code to move edges logic to workflow thread
- Add unit tests

fix(sdk-dotnet): fix do else if implementation when it is called between other LH statements

---

.github/workflows/branch.yml
.github/workflows/tests.yml

This changes the way to skip test by commits:
```sh
git commit -m "docs: add something to docs" -m "[skip main]"
git commit -m "docs: add something to docs" -m "[skip test]"
```

ci: update commit message snippet for skipping tests

---

schemas/internal/command.proto
sdk-go/lhproto/external_event.pb.go
sdk-java/src/main/java/io/littlehorse/sdk/common/proto/CorrelatedEventConfig.java
sdk-java/src/main/java/io/littlehorse/sdk/common/proto/CorrelatedEventConfigOrBuilder.java
sdk-js/src/proto/external_event.ts
server/src/main/java/io/littlehorse/common/model/corecommand/subcommand/UpdateCorrelationMarkerModel.java
server/src/main/java/io/littlehorse/common/model/getable/core/wfrun/subnoderun/ExternalEventNodeRunModel.java
server/src/main/java/io/littlehorse/common/proto/Command.java
server/src/main/java/io/littlehorse/common/proto/CommandOrBuilder.java
server/src/main/java/io/littlehorse/common/proto/CommandOuterClass.java
server/src/main/java/io/littlehorse/common/proto/UpdateCorrelationMarkerPb.java
server/src/main/java/io/littlehorse/common/proto/UpdateCorrelationMarkerPbOrBuilder.java

- Renamed UpdateCorrelationmarkerPb to UpdateCorrelationMarkerPb
- Fixes #1957

chore(server): fix capitalization on updatecorrelationmarkerpb

---

server/src/test/java/e2e/CorrelatedEventTest.java
test-utils/src/main/java/io/littlehorse/test/WfRunVerifier.java
test-utils/src/main/java/io/littlehorse/test/internal/step/DeleteUserTaskRunCommentStep.java
test-utils/src/main/java/io/littlehorse/test/internal/step/EditUserTaskRunCommentStep.java
test-utils/src/main/java/io/littlehorse/test/internal/step/SendCorrelatedEventStep.java
test-utils/src/main/java/io/littlehorse/test/internal/step/UserTaskRunCommentStep.java

chore(server): make correlated event native to e2e

---

server/src/main/java/io/littlehorse/common/model/corecommand/subcommand/DeleteWfRunRequestModel.java
server/src/main/java/io/littlehorse/common/model/corecommand/subcommand/ExternalEventTimeoutModel.java
server/src/main/java/io/littlehorse/common/model/getable/core/wfrun/subnoderun/ExternalEventNodeRunModel.java
server/src/main/java/io/littlehorse/server/streams/stores/BaseStoreImpl.java
server/src/test/java/e2e/CorrelatedEventTest.java

chore(server): clean up correlation marker when wfrun deleted

---

dashboard/src/actions/search.ts
dashboard/src/components/metadata/metadata-search-client.tsx
dashboard/src/utils/ui/constants.tsx

fix(dashboard): remove taskrun from metadata search

---

dashboard/src/components/diagram/left-sidebar/tab-content/wf-run-tab.tsx
dashboard/src/utils/ui/constants.tsx

feat(dashboard): enhance time range display and add new time range options

---

dashboard/src/components/diagram/right-sidebar/nodes/exit.tsx
dashboard/src/components/diagram/right-sidebar/nodes/external-event.tsx
dashboard/src/components/diagram/right-sidebar/nodes/sleep.tsx
dashboard/src/components/diagram/right-sidebar/nodes/start-multiple-threads.tsx
dashboard/src/components/diagram/right-sidebar/nodes/start-thread.tsx
dashboard/src/components/diagram/right-sidebar/nodes/task.tsx
dashboard/src/components/diagram/right-sidebar/nodes/throw-event.tsx
dashboard/src/components/diagram/right-sidebar/nodes/user-task.tsx
dashboard/src/components/diagram/right-sidebar/nodes/wait-for-threads.tsx
dashboard/src/utils/data/variables.ts

fix(dashboard) use `getVariable`

---

server/src/main/java/io/littlehorse/server/auth/internalport/InternalCallCredentials.java
server/src/main/java/io/littlehorse/server/streams/BackendInternalComms.java
server/src/main/java/io/littlehorse/server/streams/CommandSender.java
server/src/test/java/io/littlehorse/server/streams/CommandSenderTest.java
server/src/test/java/io/littlehorse/utils/CompletedListenableFuture.java
server/src/test/java/io/littlehorse/utils/FailedListenableFuture.java

fix(server): Async remote wait for command

---

.github/workflows/publish-docker.yml
docker/server/Dockerfile

- Server Docker image uses `installDist` binaries 
- Standalone Docker image keeps using server shadowJar

fix(pipeline): Publish server docker image

---

server/src/main/java/io/littlehorse/server/streams/taskqueue/OneTaskQueue.java
server/src/main/java/io/littlehorse/server/streams/taskqueue/PollTaskRequestObserver.java
server/src/test/java/io/littlehorse/server/streams/taskqueue/OneTaskQueueTest.java

Properly handle cases where a task gets claimed twice during a rebalance.

fix(server): Proper handle task already claimed case
