littlehorse-enterprises/littlehorse

- e2e-tests/src/main/java/io/littlehorse/tests/cases/lifecycle/AEImproperTaskNode.java
- server/src/main/java/io/littlehorse/common/LHDAO.java
- server/src/main/java/io/littlehorse/common/model/command/subcommandresponse/DeleteObjectReply.java
- server/src/main/java/io/littlehorse/server/KafkaStreamsServerImpl.java
- server/src/main/java/io/littlehorse/server/streamsimpl/coreprocessors/CommandProcessor.java
- server/src/main/java/io/littlehorse/server/streamsimpl/coreprocessors/KafkaStreamsLHDAOImpl.java
- server/src/main/java/io/littlehorse/server/streamsimpl/storeinternals/GetableStorageManager.java
- server/src/main/java/io/littlehorse/server/streamsimpl/storeinternals/LHROStoreWrapper.java
- server/src/main/java/io/littlehorse/server/streamsimpl/storeinternals/LHStoreWrapper.java
- server/src/main/java/io/littlehorse/server/streamsimpl/storeinternals/TagStorageManager.java
- server/src/main/java/io/littlehorse/server/streamsimpl/storeinternals/index/CachedTag.java
- server/src/main/java/io/littlehorse/server/streamsimpl/storeinternals/index/TagsCache.java
- server/src/main/java/io/littlehorse/server/streamsimpl/storeinternals/utils/StoredGetable.java
- server/src/main/java/io/littlehorse/server/streamsimpl/util/GETStreamObserver.java
- server/src/main/java/io/littlehorse/server/streamsimpl/util/GETStreamObserverNew.java
- server/src/main/java/io/littlehorse/server/streamsimpl/util/GETStreamObserverPepe.java
- server/src/test/java/io/littlehorse/io/littlehorse/server/streamsimpl/storeinternals/GetableStorageManagerTest.java
- server/src/test/java/io/littlehorse/server/streamsimpl/storeinternals/TagStorageManagerTest.java
In this first optimization PR we wanted to achieve two things:
1. Store the entities together with the tags cache to reduce 1 get and 1 put every time we inserted/updated something
2. Reduce the complexity of the KafkaStreamsLHDAOImpl by moving the "ORM"/"Transactional" logic into the GetableStorageManager
At first we tried to do this optimization/refactor in a big bang way but we encountered a lot of compilation errors and around 30+ files with changes. So we decided to do it incrementally by first introducing it to the "Run" entities. This PR introduces the optimization to the NodeRun, TaskRun, UserTaskRun, WfRun, and TaskWorkerGroup.
> Optimization 2/incremental combine tags cache getable

- e2e-tests/src/main/java/io/littlehorse/tests/cases/workflow/AIConditionalsLessThan.java
- e2e-tests/src/main/java/io/littlehorse/tests/cases/workflow/AJConditionalsLessThanEq.java
- e2e-tests/src/main/java/io/littlehorse/tests/cases/workflow/AKConditionalsGreaterThan.java
- e2e-tests/src/main/java/io/littlehorse/tests/cases/workflow/AMConditionalsIn.java
- server/src/main/java/io/littlehorse/server/streamsimpl/storeinternals/GetableStorageManager.java
It appears that IntelliJ and VSCode use different java linters. This fixes some errors and warnings that were present (and quite annoying) in the VSCode one.
> minor changes to make red hat's java plugin happier

- server/src/main/java/io/littlehorse/common/LHConfig.java
- server/src/main/java/io/littlehorse/server/KafkaStreamsServerImpl.java
- server/src/main/java/io/littlehorse/server/streamsimpl/ServerTopology.java
- server/src/main/java/io/littlehorse/server/streamsimpl/coreprocessors/CommandProcessor.java
- server/src/main/java/io/littlehorse/server/streamsimpl/coreprocessors/KafkaStreamsLHDAOImpl.java
- server/src/main/java/io/littlehorse/server/streamsimpl/storeinternals/LHStoreWrapper.java
Separates metadata into its own processor. The separation is meant to be done incrementally, right now it was implemented with the fewest code changes possible. In a future commit we will be refactoring the code so that Metadata and Run processors do not share the same DAO and CommandProcessor classes.
**Note:** Search is not working. Everything else is, at least everything that is covered by e2e tests.
> Separate metadata processor

- server/src/main/java/io/littlehorse/common/LHConfig.java
I forgot to add the creation of the metadata changelog topic previously so I added it now. Plus, I refactored the getAllTopics() method to explicitly show the topics that are being created and their configurations. It's more lines of codes than before, but I think that they are easier to read and understand what topics are being created. Let me know if you like the refactor, otherwise I can take it back to how it was.
> Creates metadata changelog topic and refactors getAllTopics

- server/src/main/java/io/littlehorse/common/LHConfig.java
allows hyphens in listener name on Protocol Map, authorization map, and advertised listeners map.
> MINOR: allows hyphens in listener name

- examples/variables/src/main/java/io/littlehorse/examples/VariablesExample.java
- sdk-java/src/main/java/io/littlehorse/sdk/wfsdk/Workflow.java
- sdk-java/src/main/java/io/littlehorse/sdk/worker/LHTaskWorker.java
- server/src/main/java/io/littlehorse/server/KafkaStreamsServerImpl.java
- server/src/main/java/io/littlehorse/server/streams/lhinternalscan/publicrequests/SearchVariableRequestModel.java
Returns a proper grpc response to client when the request specifies a variable that doesn't exist, doesn't have an index, or has a different type than requested in Search Variable rpc.
> Variable Search Improvement

- local-dev/README.md
- local-dev/build.sh
- local-dev/util/Dockerfile.server-quick
Adds a --quick option to local-dev/build.sh which uses local gradle cache to build.
> --quick option for local docker build

- server/src/main/java/io/littlehorse/server/streams/BackendInternalComms.java
We didn't set the partition on the request, so proto made it default to 0. Some learnings:
* We need to start running e2e-tests in a distributed environment (not just one server)
* I ran them with a 3-node cluster on my local box. Flakiness increases quite a bit, but eventually it passed. Specifically, metadata propagation takes longer and is harder to verify.
> fixes BackendInternalComms#getObject()

- lhctl/cmd/task_run.go
- server/src/main/java/io/littlehorse/server/streams/lhinternalscan/publicrequests/SearchTaskRunRequestModel.java
Problems:
* Didn't properly configure earliest/latest flags on lhctl command, resulting in a zero-second time window for all searches.
* fixe NPE on server-side when searching by taskDefName without status.
> fixes lhctl search taskRun

- sdk-python/littlehorse/worker.py
- server/src/main/java/io/littlehorse/common/model/getable/core/taskrun/TaskNodeReferenceModel.java
- now print stacktrace in console logs rather than swallow it
- log the stacktrace back to LH Server so it is reported with the WfRun.
> Fix python task worker error handling logs:

- gradle.properties
- server/src/main/java/io/littlehorse/common/LHServerConfig.java
- Standby tasks, global consumer, and restoring active tasks now fetch from followers
- Processing Active Tasks still fetch from the leader to ensure lowest latency possible
- Enable rack-aware task assignment for standby replicas
Streams config cleanup:
- Remove ill-advised fetch.max.wait.ms=20 config, which incurred unnecessary load on brokers and also extra network traffic.
- Increase request timeout to 60 seconds
- Increase transaction timeout to 60 seconds
- Ensure that all request timeouts (consumer, producer, admin client) use the same config
> Properly utilizes the Rack ID configuration in the LH Server Config:

- lh-test/src/main/java/io/littlehorse/test/internal/TestContext.java
- server/src/test/java/e2e/WaitForThreadsTest.java
- dont reuse same workflow name parallel-approval
- Ignore already exist errors on external event def's which makes ExternalBootstrapper work better
> Two fixes to test harness:

- sdk-java/src/main/java/io/littlehorse/sdk/wfsdk/internal/WorkflowThreadImpl.java
- sdk-java/src/test/java/io/littlehorse/sdk/wfsdk/internal/WorkflowThreadImplTest.java
Fixes issue in Java SDK where we add an unneeded exit node if the user calls `WorkflowThread#fail()` as the last invocation in the workflow thread building function. No impact on actual workflow execution; just makes the dashboard look confusing.
> MINOR: Remove Dangling Exit Node

- sdk-go/common/lh_variables.go
- sdk-go/wflib/wf_lib_internal.go
- sdk-go/wflib/wf_lib_internal_test.go
Previously, the common.GetVarType() function did not work when a VariableValue was passed in. This was due to improper inspection of the Go Protobuf Oneof, which has been fixed and tested in this PR.
> Go SDK Variable Type Fix

- lhctl/cmd/version.go
- server/src/main/java/io/littlehorse/server/KafkaStreamsServerImpl.java
Updates lhctl version to 0.7.0 in preparation for the release. TODO: this needs to be automated in our release script.
> MINOR: updates lhctl version.

- examples/user-tasks/src/main/java/io/littlehorse/examples/UserTasksExample.java
- server/src/main/java/io/littlehorse/common/model/metadatacommand/subcommand/PutUserTaskDefRequestModel.java
- server/src/main/java/io/littlehorse/common/util/UserTaskUtil.java
- server/src/test/java/e2e/UserTaskIdempotencyTest.java
- server/src/test/java/io/littlehorse/common/util/UserTaskUtilTest.java
Adds idempotency to UserTask.
It will accept and compare a new userTask request to the previous version stored and verify equality using `UserTaksUtil.equals` static method.
If equals returns true, then no new version will be created and the current spec will be returned.
If equals returns false, then a new version will be created
It includes utils tests and e2e tests and updates `examples/user-task` to remove no longer required existence checks.
> PutUserTaskDefRequest idempotency

- examples/basic/src/main/java/io/littlehorse/examples/BasicExample.java
- server/src/main/java/io/littlehorse/common/model/metadatacommand/subcommand/PutTaskDefRequestModel.java
- server/src/main/java/io/littlehorse/common/util/TaskDefUtil.java
- server/src/test/java/e2e/TaskDefIdempotencyTest.java
- server/src/test/java/io/littlehorse/common/util/TaskDefUtilTest.java
Enable idempotency on PutTaskDefRequest
> Enable idempotency to PutTaskDefRequest

- sdk-go/common/lh_variables.go
- sdk-go/common/lh_variables_test.go
- sdk-python/littlehorse/worker.py
1. `lhctl` was failing to pick up INT and DOUBLE input variables
2. Python SDK was not discriminating between errors with serialization and task execution
> Minor Fixes

- server/src/main/java/io/littlehorse/common/LHServerConfig.java
The LHServerConfig still referred to an unused topic '{LHS_CLUSTER_ID}-observability', and had unused methods for the Metadata Changelog topic name.
> MINOR: Removes Unused Topic

- .github/workflows/branch.yml
- .github/workflows/publish-docker.yml
While building the docker image, pnpm creates symbolic links to dependencies that cannot be recovered with a cache action through artifacts.
This disable the artifact action but instead builds the artifact for standalone and dashboard images.
> Rebuild dashboard for standalone and dashboard docker images

- .github/workflows/branch.yml
- .github/workflows/publish-docker.yml
- dashboard/package.json
Forgot to add the `cache-dependency-path` on node setup action,
This also adds the functionality to push standalone images to the private registry
> Fix broken docker publish

- e2e-tests/build.gradle
- e2e-tests/src/main/java/io/littlehorse/tests/cases/workflow/ATInterruptsBasic.java
- server/src/main/java/io/littlehorse/common/model/getable/core/wfrun/ThreadRunModel.java
- server/src/main/java/io/littlehorse/common/model/getable/core/wfrun/WfRunModel.java
- server/src/main/java/io/littlehorse/common/model/getable/global/wfspec/variable/VariableMutationModel.java
- server/src/test/java/e2e/VarSubErrorTest.java
When a ThreadSpec attempts to mutate a real variable (but that variable is out of scope for that threadspec) the server threw an NPE and ignored the Command that triggered the advance that resulted in reading that variable.
The proper behavior is for the illegal access to throw an LHVarSubError.
This commit adds a failing e2e test for that case and fixes it. However, the e2e test has apparently discovered another bug related to moving a failed thread from HALTED to ERROR, which will be addressed in subsequent commits.
> FIX: NPE when accessing variable outside of scope.

- docker/dashboard/Dockerfile
This enables the docker image to expose the service on any host. The current setup only admits to listen on localhost which is okay for a local setup but on kubernetes it would require to setup the environment variable `HOSTNAME` to expose it through a service. 
Using `0.0.0.0` by default would make it easier to use because must likely you'll need to change the hostname anyway.
> Expose dashboard on 0.0.0.0

- dashboard/apps/web/app/(main)/components/metrics/TaskExecutionMetrics.tsx
- dashboard/apps/web/app/(main)/components/metrics/WorkflowExecutionMetrics.tsx
- dashboard/apps/web/app/(main)/components/search/MetadataSearchTable.tsx
- dashboard/apps/web/app/(main)/sections/MetadataSearch.tsx
- dashboard/packages/eslint-config-custom/next.js
- dashboard/packages/ui/components/Loader.tsx
Show a `No data available` instead of persisting the `Loading...` message.
Fixes #410
This doesn't solve the issue in inner pages and will be fixed through #676
> Handle dashboard loading when there's no data

- server/src/main/java/io/littlehorse/server/streams/taskqueue/OneTaskQueue.java
- server/src/test/java/io/littlehorse/server/streams/taskqueue/OneTaskQueueTest.java
Previous implementation was incorrect in keeping track of whether there are more tasks on disk.
> FIX: internal task queue concurrency

- server/src/main/java/io/littlehorse/common/model/metadatacommand/subcommand/PutPrincipalRequestModel.java
- server/src/test/java/io/littlehorse/common/model/metadatacommand/PrincipalAdministrationTest.java
- test-utils/src/main/java/io/littlehorse/test/LHExtension.java
This PR enables LH server to create principal without specifying any tenant. This is useful when clients need to create principal that are able to do any operation in any tenant. 
The principal requester must have admin privileges:
- `ACL_ALL_RESOURCES`
- `ALL_ACTIONS`
> Create principals with admin privileges and no tenant

- server/src/main/java/io/littlehorse/common/model/metadatacommand/subcommand/PutPrincipalRequestModel.java
This commit adds a check to ensure that the principal ID provided does not contain slashes. If the ID contains a slash ("/"), it throws a LHApiException with an INVALID_ARGUMENT status, indicating that slashes are not allowed in the principal ID.
This validation helps maintain data integrity and prevents potential issues with principal IDs.
Issue 456
> Add validation for principal ID containing slashes

- .github/workflows/tests.yml
It fixed the pnpm version to be run during tests.
> ci(dashboard): use setup-node to handle cache and pnpm/actions-setup

- server/src/main/java/io/littlehorse/common/LHServerConfig.java
`linger.ms` is the time that the Kafka Producer waits to batch events before sending the request.
This PR allows configuring it on the GRPC producer, which is the thing that sends `Command`s to Kafka. Interestingly, with a single Task Worker and 8 threads, having `LHS_LINGER_MS=10` actually _slows down_ the throughput, because more of the time is spent blocking.
However, we should have this config and test it in a larger use-case with dozens of task workers all polling and sending tasks at the same time. With only one client, the advantages of batching are limited. With many, we can improve our efficiency quite a bit.
> Introduces LHS_KAFKA_LINGER_MS configuration

- local-dev/compile-proto.sh
This was replaced with `sdk-js` so there's no need to compile proto for the dashboard specifically.
> fix(proto): remove proto build for dashboard

- server/src/main/java/io/littlehorse/common/LHServerConfig.java
In the CommandProcessor, we log the 'config.getLHInstanceName()'. When the LHS_INSTANCE_ID is not set, this causes the 'ConfigBase.java' to do a WARN log of 'LHS_INSTANCE_ID not set'.
This is a short-term fix to just not do that log every time. The long term fix is that the getOrSetDefault(foo, null) should make ConfigBase 'remember' that the key 'foo' has already been asked for, so it only does the WARN log on the first time.
> MINOR: Cache instance name

- CONTRIBUTING.md
Added new sections "Examples" and "Writing a Pull Request" to `CONTRIBUTING.MD` document to enhance the new developer experience.
Once decided upon, further additions should be made to this document that outline if and how users should approach creating issues, reporting bugs.
> docs: add examples and PR guidelines to contributing doc

- sdk-java/src/main/java/io/littlehorse/sdk/worker/internal/PollThread.java
- sdk-java/src/main/java/io/littlehorse/sdk/worker/internal/RebalanceThread.java
When PollThreads stop running for any reason, a private boolean in the PollThread class `stillRunning` is set to false. Until now, this variable wasn't being used in the RebalanceThread, so when PollThreads stopped running they would never start up again.
This pull request attempts to remedy this by checking the state of the PollThread in the RebalanceThread. If the PollThread `isRunning` variable is true, it is kept. If the PollThread `isRunning` variable is false, it is replaced with a new PollThread.
Refs: #826
> fix(java-sdk): Detect if poll thread stops running and re-establish connection

- README.md
Restores logo and badges referencing a specific commit hash.
This is how it looks currently:
After this commit is merged:
> docs(readme): fix logo and badges

- dashboard/src/app/(authenticated)/taskDef/[name]/components/TaskDef.tsx
This is cause of the incorrect use of the falsey operator `||`
> fix(dashboard): threadRunNumber 0 is valid now

- server/src/main/java/io/littlehorse/server/monitoring/metrics/InstanceState.java
There was a refactor made that removes this log, which made me sad. This fixes it so that the Core Topology is logged the same as the Timer Topology (actually, Core is more important to log anyways :wink: )
> chore(server): logs core topology KafkaStreams state

- sdk-python/littlehorse/workflow.py
- sdk-python/tests/test_workflow.py
Implements `timeout_seconds` property for Tasks in the Python SDK.
1. Python SDK users can customize the timeout length of TaskNodes from the `WorkflowThread.execute()` method.
The following example defines a workflow that executes the "greet" `TaskDef` with a `timeout_seconds` value of `40` seconds. 
```python
def get_workflow() -> Workflow:
def my_entrypoint(wf: WorkflowThread) -> None:
wf.execute("greet", the_name, timeout_seconds=40)
return Workflow("example-basic", my_entrypoint)
```
---------
2. Python SDK users can also set a Workflow-wide default `timeout_seconds` value using
the `Workflow.with_task_timeout_seconds()` method.
The following example defines a workflow that executes two tasks, one that uses a default timeout (5 seconds) and one that uses a custom defined one (10 …
> feat(python-sdk): Add customizable timeout for workflow `TaskRuns`

- server/src/main/java/io/littlehorse/server/monitoring/health/ServerHealthState.java
This PR fixes the issue where the `/status` endpoint wasn't returning an empty list for the standby states.
However, I think there is some other issue. While constantly running 5 workflow's per second (so the changelog topics should have stuff being produced to them), I see the following numbers _never get updated_ which means probably the `onBatchRestored()` isn't getting called...?
```
"partition": 42,
"lag": 16960,
"changelogEndOffset": 34322
```
The `lag` never changes, nor does the `changelogEndOffset`, except on a rebalance.
> fix(server): report on standby lag

- .github/workflows/analysis.yml
- .github/workflows/branch.yml
- .github/workflows/publish-docker.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- sdk-java/src/main/java/io/littlehorse/sdk/common/proto/VariableType.java
Takes care of deprecated version of GitHub actions used for **checking out** and **setting up Java** by upgrading both actions to version 4.
> Upgrades checkout and setup-java actions to version 4

- local-dev/Dockerfile
- local-dev/compile-proto.sh
This PR enables compile-proto.sh to run with on `aarch_64` and `x86_64`
Here some findings while making this change:
- The package `github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc`  is outdated and is no longer compatible with newer golang versions.
- Upgrading protobuf to latest version requires additional changes for `sdk-java` since some of the utility classes were renamed.
- More architectures can be added by modifying the compile-proto.sh accordingly.
> chore(protobuf): generate protobuf files from x86_64 and aarch_64

- dashboard/src/app/(authenticated)/(diagram)/components/NodeTypes/Task/TaskDetails.tsx
Fixes issue reported by @MateoRojas while clicking `"Inspect TaskRun"` on a tenant.
> fix(dashboard): handle tenantId for taskRuns

- server/src/main/java/io/littlehorse/server/monitoring/metrics/InstanceState.java
This caused unclean shutdowns in the kafka streams instance. Follow up PR will be created after this to implement a proper mechanism to handle uncaught exceptions in kafka streams.
> fix(server): fixes rebalance implementation during instance shutdowns

- e2e-tests/src/main/java/io/littlehorse/tests/Test.java
- sdk-java/build.gradle
- sdk-java/src/main/java/io/littlehorse/sdk/common/LHLibUtil.java
- sdk-java/src/main/java/io/littlehorse/sdk/common/exception/LHJsonProcessingException.java
- sdk-java/src/main/java/io/littlehorse/sdk/worker/internal/util/VariableMapping.java
- server/build.gradle
- server/src/test/java/e2e/FailureHandlingTest.java
- server/src/test/java/e2e/JsonMutationTest.java
- server/src/test/java/e2e/VarMutationListsTest.java
Shouldn't include the Jackson libraries as part of the API of sdk-java, since our users might have it in a different version which conflicts with the one provided by our library.
> chore(sdk-java): don't include jackson in api

- e2e-tests/src/main/java/io/littlehorse/tests/Test.java
- sdk-java/build.gradle
- sdk-java/src/main/java/io/littlehorse/sdk/common/LHLibUtil.java
- sdk-java/src/main/java/io/littlehorse/sdk/common/auth/TenantMetadataProvider.java
- sdk-java/src/main/java/io/littlehorse/sdk/common/config/LHConfig.java
- sdk-java/src/main/java/io/littlehorse/sdk/common/exception/LHJsonProcessingException.java
- sdk-java/src/main/java/io/littlehorse/sdk/worker/internal/util/VariableMapping.java
- server/build.gradle
- server/src/test/java/e2e/FailureHandlingTest.java
- server/src/test/java/e2e/JsonMutationTest.java
- server/src/test/java/e2e/VarMutationListsTest.java
- server/src/test/java/io/littlehorse/common/LHConfigTest.java
- test-utils/src/main/java/io/littlehorse/test/LHExtension.java
- test-utils/src/main/java/io/littlehorse/test/internal/StandaloneTestBootstrapper.java
- LHConfig#getTenantId() now returns a TenantId not a String
- When getting a GRPC stub from the LHConfig and passing in a TenantId, fixes issue where we dropped the OAuth credentials resulting in UNAUTHENTICATED errors.
> refactor(sdk-java): TenantId Management

- docs/docs/05-developer-guide/08-wfspec-development/05-interrupts.md
From the interrupt handler doc make a link to the instructions on how to post a new external event.
> docs: Adds reference to the post external events doc

- server/src/main/java/io/littlehorse/server/KafkaStreamsServerImpl.java
- server/src/main/java/io/littlehorse/server/streams/BackendInternalComms.java
- server/src/main/java/io/littlehorse/server/streams/util/AsyncWaiters.java
- server/src/main/java/io/littlehorse/server/streams/util/POSTStreamObserver.java
- server/src/test/java/io/littlehorse/server/streams/util/AsyncWaitersTest.java
- Uses network thread pool for internal GRPC clients to reduce number of total threads used by server
- Uses network thread pool to clean up old command waiters
- Fixes stack overflow error on the wait for command retry logic and avoids busy waiting by using network thread pool to schedule retries later.
> fix(server): don't busy-retry on wait-for-command

- .github/workflows/tests.yml
@mijailr brought up a good point about allowing outside collaborators to run workflows on pull requests, see the below 
- https://github.com/ossf/scorecard/issues/3827
Proper solution:
- https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
> fix(ci): Revert test workflow triggers

- gradle.properties
Upgrade kafka versions. StateUpdater is now enabled by default in kafka 3.8.
> chore(server): Upgrade kafka version

- docs/docusaurus.config.js
This PR adds the Algolia DocSearch Bar to our Docusaurus Documentation deployed at [https://www.littlehorse.dev/](https://www.littlehorse.dev/).
Algolia Search for Docusaurus is a free service provided by Algolia that crawls our documentation once a week, updating its internal index and exposing it on a public search endpoint.
This PR contains a public API key provided by Algolia. Their documentation says it is okay to expose their public API key in our version control [link](https://docsearch.algolia.com/docs/DocSearch-program#can-i-share-the-apikey-in-my-repo) and that it is pre-configured with rate-limiting [link](https://www.algolia.com/doc/guides/security/api-keys/in-depth/api-key-restrictions/).
Here are additional resources to learn about Algolia DocSearch:
- [Docusaurus …
> docs: Add Algolia DocSearch to docs website

- docs/docs/06-operations/10-docker-compose/15-three-servers.md
This PR adds a page to our documentation with instructions on how to run the Three Servers docker compose example.
> docs(examples): Add page for using Three Server docker compose example

- .github/workflows/tests.yml
When an external contributor creates a pull request from a fork, it's not being triggered. This is intended to fix that.
> ci(tests): run tests on pull requests

- .github/workflows/publish-docker.yml
This can be added later to the shared GitHub Action.
> ci(docker): add tags for branch events

- lhctl/README.md
Updates the README.md for installing `lhctl` from local source code to include new Go Workspace install instructions.
> Update `lhctl` install guide

- .github/workflows/release.yml
From golang `1.20` the `go.mod` version format had changed.
> ci(lhctl): use golang 1.21.3

- .github/workflows/publish-docker.yml
- .github/workflows/release.yml
- docker/lhctl/Dockerfile
- server/src/main/java/io/littlehorse/server/Version.java
- server/src/test/java/io/littlehorse/server/VersionTest.java
Fixes some issues with the advertised version for lh-server and lhctl docker image.
For `lhctl` now we pass two variables `VERSION` and `COMMIT` which are set as build args and in consequence the resulting `lhctl` binary will output the correct version when calling `lhctl version` from the docker image.
For `lh-server` the version class was adding the `PreReleaseIdentifier` as empty string, which caused lhctl to print an additional character `-`. Also after the version replacement occurs during a release, the test was expecting to have a static value `0.0.0-development` but during the production build that value would change. So I refactored the test to be flexible enough to validate the version to be published.
> build(server): use tag version on server artifact

- server/src/main/java/io/littlehorse/common/model/getable/global/wfspec/node/NodeModel.java
- server/src/test/java/io/littlehorse/common/model/getable/global/wfspec/node/NodeModelTest.java
This PR solves a bug when clients try to handle technical errors in a wfspec:
`NodeOutput node = wf.execute("fail");
wf.handleError( // Handle technical failure
node,
LHErrorType.TIMEOUT,
handler -> {
handler.execute("my-task");
}
);`
> fix(server): Ignore predefined errors when validating specific failures

- examples/interrupt-handler/README.md
- lhctl/internal/post_event.go
Null variable value is not longer supported by Littlehorse server.
> fix(lhctl): Post events with empty payload

- docs/src/css/custom.css
- Added new color to links site wide.
- Added underline and bold weight to links in paragraph elements (in page bodies effectively).
--------------------------
> docs(style): Add text decoration and new color to links

- docs/docusaurus.config.js
Adds `aria-label` attribute describing navbar icons to improve accessibility performance.
> docs: Add aria labels to navbar icons

- dashboard/src/app/(authenticated)/(diagram)/components/NodeTypes/ExternalEvent/ExternalEvent.tsx
- dashboard/src/app/(authenticated)/externalEventDef/[name]/components/ExternalEventDef.tsx
- dashboard/src/app/(authenticated)/taskDef/[name]/components/TaskDef.tsx
- dashboard/src/app/utils/date.ts
- Timeouts are now shown
- Timeouts are formatted 165 seconds -> "2m 45s"
- `Inspect TaskRun` -> `Inspect ExternalEvent`
- `Inspect ExternalEvent` only shown once `ExternalEvent` has been called
> fix(dashboard): better external event UX

- .github/workflows/master.yml
- docs/src/css/custom.css
The Docusaurus build tool uses the "advanced cssnano preset" and several plugins that break our CSS file upon building the production version of our documentation.
This PR adds an environment variable setting to disable the advanced CSS minifier and use the default CSS minifier settings.
See this Docusaurus link for more info: https://docusaurus.io/docs/cli#docusaurus-build-sitedir
> docs: Fix CSS by disabling advanced CSS minifier

- sdk-dotnet/Examples/BasicExample/Program.cs
- sdk-dotnet/LittleHorse.Sdk.Tests/LHInputVariablesTest.cs
- sdk-dotnet/LittleHorse.Sdk/LHConfig.cs
- sdk-dotnet/LittleHorse.Sdk/LHInputVariables.cs
- Add constructor to build LHConfig from a dictionary
- Add unit tests
- Change basic example
> feat(dotnet-sdk): read config variables from dictionary

- sdk-go/littlehorse/wf_lib_internal.go
- sdk-go/littlehorse/wf_lib_internal_test.go
- sdk-go/littlehorse/wf_lib_public.go
- sdk-java/src/main/java/io/littlehorse/sdk/wfsdk/WfRunVariable.java
- sdk-java/src/main/java/io/littlehorse/sdk/wfsdk/internal/WfRunVariableImpl.java
- sdk-python/littlehorse/model/__init__.py
- sdk-python/littlehorse/workflow.py
- sdk-python/tests/test_workflow.py
- server/src/main/java/io/littlehorse/common/model/corecommand/subcommand/TriggeredTaskRun.java
- server/src/main/java/io/littlehorse/common/model/getable/global/wfspec/WfSpecModel.java
- server/src/main/java/io/littlehorse/common/model/getable/global/wfspec/thread/ThreadSpecModel.java
- server/src/main/java/io/littlehorse/common/model/getable/global/wfspec/thread/ThreadVarDefModel.java
- server/src/main/java/io/littlehorse/common/model/getable/global/wfspec/variable/JsonIndexModel.java
- server/src/main/java/io/littlehorse/common/model/getable/global/wfspec/variable/VariableDefModel.java
- server/src/main/java/io/littlehorse/common/util/WfSpecUtil.java
- server/src/test/java/e2e/SharedVariablesTest.java
- server/src/test/java/e2e/WfSpecLifecycleTest.java
- server/src/test/java/io/littlehorse/common/model/getable/global/wfspec/WfSpecModelTest.java
- Fixes ticket #582
- Default access level is now PRIVATE
- Only PUBLIC_VAR and required input variables are considered in WfSpec versioning
- Only PUBLIC_VAR can be frozen
> feat(server)!: changes variable access level api

- server/src/main/java/io/littlehorse/common/LHServerConfig.java
In testing, I observed that when moving from a 3-node Kafka cluster with mixed brokers and controllers to a Kafka cluster with separate brokers and controllers, all of the Kafka clients got stuck and continued trying to connect to the controllers which no longer had the broker role.
It turns out that KIP-899 indirectly solves this problem by allowing clients to re-bootstrap and discover which servers are the brokers now. When tested with my fix for KAFKA-17455, we are successfully able to continue processing workflows without a crash / TaskCorruptedException when migrating the Kafka Cluster from mixed mode to separate mode.
> feat(server): use kip-899 to rebootstrap clients

- dashboard/package-lock.json
- dashboard/src/app/(authenticated)/components/tables/WfSpecTable.tsx
Fixes error on failed run of dashboard job, which says:
```
./src/app/(authenticated)/components/tables/WfSpecTable.tsx
18:3  Error: React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return?  react-hooks/rules-of-hooks
```
Job Run Link: https://github.com/littlehorse-enterprises/littlehorse/actions/runs/11967285971/job/33391162714
> fix(dashboard): Move useEffect so that it is not called conditionally

- lhctl/internal/principal.go
- server/src/main/java/io/littlehorse/server/streams/lhinternalscan/publicrequests/SearchPrincipalRequestModel.java
Removes requirement for one of `principal_criteria` field to be submitted with each `SearchPrincipalRequest` from server and lhctl.
Resolves #1152.
> fix(server): Support blank `SearchPrincipalRequest`

- sdk-dotnet/LittleHorse.Sdk.Tests/Helper/LHMappingHelperTest.cs
- sdk-dotnet/LittleHorse.Sdk.Tests/LHTaskSignatureTest.cs
- sdk-dotnet/LittleHorse.Sdk/Helper/LHMappingHelper.cs
- sdk-dotnet/LittleHorse.Sdk/Worker/LHTaskSignature.cs
- sdk-dotnet/Littlehorse.sln
- Create validation to not build schema output when there is not return type in LH Task Methods
- Change Mapping Type method to return JSON obj when a param or return type is not between the allowed primitive types
- Add and modify unit tests
> fix(dotnet-sdk): refactor task signature to not build schema output with no return type

- docs/docs/08-api.md
- schemas/littlehorse/user_tasks.proto
- sdk-go/lhproto/user_tasks.pb.go
- sdk-java/src/main/java/io/littlehorse/sdk/common/proto/UserTaskTriggerReference.java
- sdk-java/src/main/java/io/littlehorse/sdk/common/proto/UserTaskTriggerReferenceOrBuilder.java
- sdk-js/src/proto/user_tasks.ts
- sdk-python/littlehorse/model/__init__.py
- server/src/main/java/io/littlehorse/common/model/getable/core/init/ServerVersionModel.java
- server/src/main/java/io/littlehorse/common/model/getable/core/taskrun/UserTaskTriggerReferenceModel.java
- server/src/test/java/e2e/UserTaskTest.java
This PR makes sure that UserTask User details are passed onto the WorkerContext when necessary by fixing a bug in the `UserTaskTriggerReferenceModel` where we failed to serialize the userId and userGroup.
This PR also adds 2 E2E tests:
- 1 covering functionality for Scheduled Reminder Tasks
- 1 covering functionality for passing UserTask User details to the WorkerContext.
> fix(server): Pass UserTask User details to WorkerContext

- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/app/[tenantId]/(diagram)/wfSpec/[...props]/components/Thread.tsx
- dashboard/src/app/[tenantId]/(diagram)/wfSpec/[...props]/components/WfRunsHeader.tsx
- dashboard/src/app/[tenantId]/components/Principal.tsx
- dashboard/src/app/[tenantId]/components/TenantSelector.tsx
- dashboard/src/app/[tenantId]/components/VersionSelector.tsx
- dashboard/src/app/[tenantId]/taskDef/[name]/components/TaskDef.tsx
- dashboard/src/app/[tenantId]/userTaskDef/[...props]/components/UserTaskDef.tsx
- dashboard/src/components/ui/accordion.tsx
- dashboard/src/components/ui/dropdown-menu.tsx
- dashboard/tailwind.config.ts
resolves [#1172](https://github.com/littlehorse-enterprises/littlehorse/issues/1172)
- Converted headlessui to our agreed upon standard of shadcn
- This unifies the codebase and UI visuals
- No longer using deprecated headlessui components
- All refactored scopes have been tested by me and are working as expected
_Videos of new components_
https://github.com/user-attachments/assets/74e6c2a7-e5b8-4695-90e5-bfb573940a23
https://github.com/user-attachments/assets/52f3ea2b-ef44-4a9e-98c7-5b135d639d99
https://github.com/user-attachments/assets/5024e1f0-41dc-40d2-961b-b03c220e4620
> refactor(dashboard): headlessui -> shadcn

- sdk-python/littlehorse/workflow.py
Adds the `WorkflowThread.declare_str` method which is missing from our latest batch of SDK changes.
> fix(sdk-python): Add missing `WorkflowThread.declare_str` method

- canary/canary.properties
- canary/src/main/java/io/littlehorse/canary/Main.java
- canary/src/main/java/io/littlehorse/canary/aggregator/internal/MetricStoreExporter.java
- canary/src/main/java/io/littlehorse/canary/aggregator/topology/MetricsTopology.java
- canary/src/main/java/io/littlehorse/canary/config/CanaryConfig.java
- canary/src/main/java/io/littlehorse/canary/metronome/internal/BeatProducer.java
- canary/src/main/proto/beats.proto
- canary/src/main/proto/metrics.proto
- canary/src/test/java/io/littlehorse/canary/aggregator/internal/MetricStoreExporterTest.java
- canary/src/test/java/io/littlehorse/canary/aggregator/topology/MetricsTopologyTest.java
- docs/CANARY_CONFIGURATIONS.md
This pull request adds support for the `dataplane_id` attribute across various components of the Canary application. The most important changes include updates to configuration files, Java classes, protocol buffer definitions, and test cases.
* Added `lh.canary.metronome.server.dataplane.id` to `canary/canary.properties` and documented it in `docs/CANARY_CONFIGURATIONS.md`
* Updated `CanaryConfig` to include methods for `dataplane_id` 
* Modified `Main.java`, `MetricStoreExporter.java`, `MetricsTopology.java`, and `BeatProducer.java` to handle `dataplane_id`
* Added `dataplane_id` to `BeatKey` and `MetricKey` in `beats.proto` and `metrics.proto` respectively
> feat(canary): add mandatory config metronome.server.dataplane.id

- canary/src/main/java/io/littlehorse/canary/Main.java
The change corrects the order of parameters in the `initialize` method to ensure `canaryConfig.getMetronomeServerDataplaneId()` is correctly placed after `canaryConfig.getMetronomeServerId()`.
> fix(canary): sort dataplaneId parameter on BeatProducer

- .github/workflows/release.yml
- .github/workflows/tests.yml
- sdk-dotnet/LittleHorse.Sdk/LittleHorse.Sdk.csproj
- Add sdk-dotnet release job
- Add sdk-dotnet tests job
> build(sdk-dotnet): Add dotnet job to release pipeline

- sdk-go/littlehorse/lh_errors.go
- sdk-go/littlehorse/lh_variables.go
- sdk-go/littlehorse/task_worker_internal.go
Allows users to pass content of any type to their LHTaskExceptions.
Users can now pass any type of content into the `Content interface{}` field of an SDK-Go `LHTaskException` and the SDK will use its internal `InterfaceToVarVal` method to convert the content into a protobuf compatible format.
> feat(sdk-go): Allow users to pass any content to LHTaskException

- sdk-go/littlehorse/wf_lib_internal.go
- sdk-go/littlehorse/wf_lib_internal_test.go
- sdk-python/littlehorse/workflow.py
- sdk-python/tests/test_workflow.py
This PR removes the dangling exit node left on WorkflowThreads that return early using the `WorkflowThread.fail()` method in `sdk-python` and `sdk-go`.
**Resolves Issue #473.**
**Applies the changes in #142 to `sdk-python` and `sdk-go`.**
A WorkflowThread that reads as follows:
```
wf.execute("some-task")
wf.fail("my-failure", "failure_message)
```
Would effectively stop at the Node created by `wf.fail()`. But the WorkflowThread builder in the SDK would add an additional ExitNode anyways, resulting in this dangling node:
The Python and Go SDKs will now check if the last node in a WorkflowThread is an exit node before adding another one.
> fix(sdk-go, sdk-python): Remove dangling exit nodes on early returned WorkflowThreads

- server/src/main/java/io/littlehorse/server/streams/storeinternals/ReadOnlyGetableManager.java
- server/src/main/java/io/littlehorse/server/streams/taskqueue/OneTaskQueue.java
- server/src/test/java/io/littlehorse/server/streams/taskqueue/OneTaskQueueTest.java
- server/src/test/java/io/littlehorse/server/streams/taskqueue/TaskQueueManagerTest.java
This PR includes a major refactor for the class `OneTaskQueue` in order to stabilize TaskRun latencies. 
There are several problems related to the task rehydration process:
- TaskQueue ordering is not really guaranteed because the current algorithm aims to execute rehydration only when the task is empty leading to a scenario where the new-arriving tasks gets executed *before* the ones that are serialized on disk.
- Task rehydration happens inside a synchronized block (lock/unlock) which means that the streams threads will be blocked until the rehydration process releases the lock. This is really bad for application instance stability.
- It is really tricky to implement an algorithm that guarantees that all serialized tasks will be rehydrated, that caused many bugs in the past. 
Changes …
> fix(server): Taskqueue ordering

- server/src/main/java/io/littlehorse/common/LHServerConfig.java
- server/src/main/java/io/littlehorse/common/util/RocksConfigSetter.java
This PR adds a server config that allows users to limit the write rate to the stores inside the core topology. 
see [Rocksdb rate limiter](https://github.com/facebook/rocksdb/wiki/rate-limiter)
> feat(server): Core store rate limiter

- dashboard/src/app/[tenantId]/page.tsx
- dashboard/src/app/[tenantId]/taskDef/[name]/components/TaskDef.tsx
- dashboard/src/app/actions/getWfSpecsByTaskDef.tsx
- Allow the user to view a list of `WfSpecs` that are used by any particular `TaskDef`.
- Via `WfSpec Usage` section under the `TaskDef` page. 
- Using same `WfSpec` display visuals as on the primary `WfSpecs` view to maintain consistency and usage expectations by the user
https://github.com/user-attachments/assets/ef3c684d-4bcf-4604-941b-843e624d6e26
> feat(dashboard): display taskdef usage by wfspecs

- server/src/main/java/io/littlehorse/server/streams/BackendInternalComms.java
- server/src/main/java/io/littlehorse/server/streams/ProducerCommandCallback.java
- server/src/test/java/io/littlehorse/server/streams/ProducerCommandCallbackTest.java
As per the documentation, Kafka producer callbacks should not execute heavy operation on the `onCompletion` because they run in the producer network thread [More details here](https://kafka.apache.org/39/javadoc/org/apache/kafka/clients/producer/KafkaProducer.html#send(org.apache.kafka.clients.producer.ProducerRecord,org.apache.kafka.clients.producer.Callback))
> perf(server): Async processing for command producer callbacks

- sdk-go/littlehorse/wf_lib_internal.go
- sdk-go/littlehorse/wf_lib_public.go
We should use the same type of `int` in our public SDK methods as is used at the `proto` level for transparency purposes.
> fix(sdk-go): Change `NodeOutput.Timeout` arg to `int64`

- sdk-go/littlehorse/lh_variables.go
We use the `InterfaceToVarVal` method to attempt to convert any value to a VariableValue, performing many steps along the way.
One of those steps checks if the value is a Pointer or not. When performing that step, if the value is `nil`, the program crashes with the following error message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0xa8 pc=0x1047e7dc0]
```
To solve this, we can return early if the value is `nil`.
> fix(sdk-go): Catch nil interface early when converting to var val

- dashboard/src/app/(authenticated)/[tenantId]/(diagram)/wfRun/[...ids]/components/WfRun.tsx
- dashboard/src/app/(authenticated)/[tenantId]/(diagram)/wfRun/[...ids]/page.tsx
resolves #890 
- Fixed url param accessing for child workflows
- If parent workflow exists, retrieve its variables and display them
> fix(dashboard): retrieve parent wf variables

- sdk-go/littlehorse/lh_variables.go
> fix(sdk-go): trim space on boolean on StrToVarVal

- docker/dashboard/Dockerfile
Pins `ghcr.io/littlehorse-enterprises/alpine-nginx-nodejs/nginx-nodejs` to version `v1`. It's a good practice to pin the version of the artifacts to avoid unintentionally using a recently released version that might contain errors. It helps to keep builds consistent.
> chore(dashboard): pins nginx-nodejs image to version v1

- dashboard/src/app/(authenticated)/[tenantId]/(diagram)/wfRun/[...ids]/components/Variables.tsx
- dashboard/src/app/(authenticated)/[tenantId]/(diagram)/wfRun/[...ids]/components/WfRun.tsx
- dashboard/src/app/(authenticated)/[tenantId]/(diagram)/wfRun/[...ids]/page.tsx
- dashboard/src/app/actions/getWfRun.ts
- dashboard/src/app/hooks/useWfRun.tsx
- Refactored the id pulled from the url, which is passed to the wfRun page component, to be formatted via WfRunId object instead of just the string
- Refactored SWR implementation to avoid running the getWfRun request if there is no valid ID present
https://github.com/user-attachments/assets/dd4c56b1-1451-49bc-8988-80197f55e8de
> fix(dashboard): wfrun blank page

- server/src/main/java/io/littlehorse/common/model/getable/core/wfrun/subnoderun/ExternalEventNodeRunModel.java
- server/src/test/java/e2e/ExternalEventTest.java
- #665 introduced a bug which prevented an ExternalEvent timeout from throwing a NodeFailureException.
- Small fix.
> fix(server): external-event timeout

- dashboard/src/app/(authenticated)/[tenantId]/components/Principal.tsx
resolves [#1294](https://github.com/littlehorse-enterprises/littlehorse/issues/1294)
- Conditionally renders sign out button depending on env var `LHD_OAUTH_ENABLED`
- Do we want to use data from next-auth to determine if auth is enabled, or the env?
> fix(dashboard): conditionally render sign out

- sdk-dotnet/Examples/ExternalEventExample/README.md
- sdk-dotnet/LittleHorse.Sdk/Workflow/Spec/NodeOutput.cs
- There were problems with a conditional thread, for a wrong variable was assigned when I used a JsonPath.
Variable assigment with problem: 
Fixed:
> fix(sdk-dotnet): add jsonpath to nodeoutput

- examples/interrupt-handler/README.md
Small but important clarification.
A thread does not need to be sleeping to use an interrupt. The previous wording may confuse some people.
> refactor(examples): readme clarification

- dashboard/src/app/(authenticated)/[tenantId]/(diagram)/components/NodeTypes/StartMultipleThreads.tsx
- Can't implement scrolling in the 2D plane data group UI, so I've resulted to the Dialog popup.
> fix(dashboard): handle large thread spec lists in tool tip

- dashboard/src/app/(authenticated)/[tenantId]/(diagram)/components/Forms/WfRunForm.tsx
- dashboard/src/app/(authenticated)/[tenantId]/(diagram)/components/Forms/components/BaseFormField.tsx
- dashboard/src/app/(authenticated)/[tenantId]/(diagram)/components/Modals/ExecuteWorkflowRun.tsx
resolves #1451
- Replace dots with a constant and unique string value
The issue was that `react-hook-form`'s naming conventions converts registered names with `.`'s in them to nested paths. The variable example in the original issue had a `.` in it, resulting in a weird incompatible object structure for the variable. This PR enables compatibility with `.`'s
> fix(dashboard): '.' replacement & conversions in form

- dashboard/src/app/utils/dateTime.ts
- Make `0` the minimum value for durations
> fix(dashboard): disallow negative durations

- .github/ISSUE_TEMPLATE/03-documentation.yml
- .github/ISSUE_TEMPLATE/config.yml
Quick PR to revise the issue templates.
- Removes a link to discussions that made the menu look bloated
- Replaces documentation emoji for better contrast
> fix(github): Revise issue templates

- server/src/main/java/io/littlehorse/server/streams/storeinternals/GetableManager.java
- server/src/main/java/io/littlehorse/server/streams/storeinternals/GetableToStore.java
- server/src/test/java/io/littlehorse/storeinternals/GetableManagerTest.java
In the GetableManager#commit() method, we previously put every single GetableToStore into rocksdb. THat's problematic because when we *read* a getable without modifying it, it ends up inside the buffer. This PR reduces the writes to RocksDB by saving the previous protobuf and comparing to the protobuf at the time of commit. This costs a bit more CPU at the server-side but reduces the number of writes to rocksdb.
> perf(server): avoid sending extra writes to rocksdb

- sdk-go/littlehorse/wf_lib_internal.go
- sdk-go/littlehorse/wf_lib_public.go
Fixes #1526 
Changes the return value of `*wfRunVariable.Jsonpath() ` to ` *wfRunVariable`  
Changes ` varType` return value from nil to `w.varType`
> fix(sdk-go):jsonpath to return reference to wfRunVariable and return correct varType

- sdk-go/littlehorse/task_func_signature.go
- sdk-go/littlehorse/task_func_signature_test.go
@Jake brought up a good question in issue #1531:
> Why doesn't the `WorkerContext` parameter work in `sdk-go` when used like this:
>
> ```go
> func TaskUsesNonPointerWorkerContext(name string, wc littlehorse.WorkerContext) string {}
> ```
This is because we require the parameter to be a pointer to a `WorkerContext`. It needs to be a pointer to a `WorkerContext` so that the user can call `WorkerContext#Log()` from within a Task and we can handle those messages from up above in the Task Worker.
It can be confusing, however, that the sdk-go accepts `littlehorse.WorkerContext` without a pointer as a valid parameter, so I wrote this PR to add an error message and some test cases around this behavior.
-------------------------
Adds an error message for #1531
> feat(sdk-go): Throw error when `WorkerContext` used as param without ptr

- dashboard/src/app/(authenticated)/[tenantId]/(diagram)/components/Forms/components/validation.ts
Removes condition placed on `JSON_ARR` inputs in the `Execute` `WfRun` form because not all Array items are guaranteed to be objects. 
For instance, the following JSON_ARR would fail the input validation because it has items of `String`s and not `Object`s:
```
["hello", "world"]
```
> fix(dashboard): Don't enforce `JSON_ARR` to include objects

- sdk-python/examples/parallel_approvals/parallel_approvals.py
- sdk-python/littlehorse/workflow.py
- sdk-python/tests/test_worker.py
- sdk-python/tests/test_workflow.py
- server/src/test/java/e2e/ExternalEventTypingTest.java
This PR adds the `complete()` method to `sdk-python`, which adds an ExitNode wherever it is used, allowing users to return early from a Workflow.
The previous implementation of `Do_If` and `Do_Else_If` code heavily depended on the idea that each Workflow has a singular sink vertex in the form of the last ExitNode (a Node with no OutgoingEdges). Therefore, that code had to be updated and the tests had to be expanded along with this PR.
You'll also notice from formatting changes to otherwise unchanged files from the linter.
> feat(sdk-python): Add `WorkflowThread#complete()`

- lhctl/internal/wf_run.go
Before this, `lhctl` was throwing a panic when you called `lhctl search wfRun` with zero arguments, which isn't very helpful. This updates the args validator to throw an error message in that case.
> fix(lhctl): Throw error if `search wfRun` called with no args 

- README.md
Previous badge was referencing the last published tag, which not necessarily is the `latest` release, this changes to point to the latest release instead.
> docs(readme): fix golang badge

- dashboard/src/components/metadata/metadata-search-client.tsx
- dashboard/src/components/metadata/metadata-table.tsx
- dashboard/src/utils/ui/constants.tsx
- Added unique workflow specification handling in the search client to prevent duplicates.
- Integrated RPC call to fetch the latest workflow specifications.
- Updated default search limit from 10 to 20 for improved user experience.
- Adjusted key handling in the metadata table for better uniqueness.
Before:
After:
> feat(dashboard): get the latest `WfSpec` version

- server/src/main/java/io/littlehorse/common/model/getable/global/wfspec/ReturnTypeModel.java
- server/src/main/java/io/littlehorse/common/model/getable/global/wfspec/TypeDefinitionModel.java
- server/src/main/java/io/littlehorse/common/util/LHUtil.java
- server/src/main/java/io/littlehorse/server/streams/lhinternalscan/publicrequests/SearchVariableRequestModel.java
This refactor relocates the `isPrimitive()` method logic from the `TypeDefinition` class.
We did this because the method doesn't actually check if a type is primitive, it only serves for deciding whether a type is searchable or not. 
We also removed some unused methods with old references to this `isPrimitive` method.
> refactor(sdk-java): Relocate `isPrimitive` logic from `TypeDefinition`

- dashboard/src/app/(authenticated)/[tenantId]/(diagram)/components/NodeTypes/Task/TaskDetails.tsx
- Added max-w to overflow component
- Changed styling of container so the style matches the rest of the sections
- Removed error varient on overflow component, because it doesn't make sense in this context.
> fix(dashboard): fix TaskAttempt worker log output overflowing

- server/src/main/java/io/littlehorse/common/LHServerConfig.java
Kafka streams sets 1000 as default value for `max.poll.records`, but that value is high in the context of littlehorse server because littlehorse server performs logic, validations and many state store operations (get, put, scans), making the server vulnerable to transaction timeouts when processing 1000 records in a single transaction. 
This PR proposes to decrease this value to 100. It will cause more `poll` requests, but this won't affect the fetching behavior.
> perf(server): Reduce the number of records in each poll request for main consumer

- server/src/main/java/io/littlehorse/common/LHServerConfig.java
- server/src/main/java/io/littlehorse/common/util/RocksConfigSetter.java
- LHS_X_USE_AT_LEAST_ONCE: removed since it is unadvisable.
- LHS_X_USE_STATE_UPDATER: removed since State Updater is now GA in Kafka Streams.
- LHS_X_LEAVE_GROUP_ON_SHUTDOWN: removed since we have functionality that relies on this being true.
- LHS_X_USE_STATIC_MEMBERSHIP: removed because it does not help and is no longer the recommended way to go in Kafka Streams.
> Remove deprecated configs

- server/src/main/java/io/littlehorse/common/util/RocksConfigSetter.java
Should reduce cpu utilization of compression.
> perf(rocksdb): compress only bottom level

- server/src/main/java/io/littlehorse/common/LHServerConfig.java
There is no use in allowing users to configure different transaction timeouts versus consumer session timeouts. This is because:
- We **want** to leave the group during shutdown (eg. rolling restart), because #838 relies on a rebalance in order to maintain availability of waitForCommand.
- Since we **want** to leave the group on shutdown, a longer session timeout won't help compared to transaction timeout.
- In the event of a crash, we need to wait for the transaction to time out anyways before the partitions can be re-claimed by another instance.
In other words, if session.timeout.ms > transaction.timeout.ms, our unavailability window will be equal to the larger of the two values.
Therefore, it's safe (and advisable) to remove one of them and use the same value for both configs. This …
> chore(server): clean up session and transaction timeout configs

- server/src/main/java/io/littlehorse/server/streams/topology/core/CoreProcessorContext.java
- server/src/main/java/io/littlehorse/server/streams/topology/core/MetadataProcessorContext.java
- server/src/main/java/io/littlehorse/server/streams/topology/core/RepartitionExecutionContext.java
- server/src/main/java/io/littlehorse/server/streams/topology/core/RequestExecutionContext.java
- server/src/main/java/io/littlehorse/server/streams/topology/core/WfService.java
Removes unused fields in `WfService`, making `ReadOnlyMetadataManager metadataManager` the only constructor parameter.
> fix(server): Remove unused fields in `WfService`

- docker/standalone/Dockerfile
This changes to use Ubuntu LTS 24.04 and Kafka 4.0.0
> fix(standalone): use ubuntu LTS 24.04

- server/src/main/java/io/littlehorse/common/LHServerConfig.java
- server/src/main/java/io/littlehorse/common/util/RocksConfigSetter.java
- Changes to LZ4 compression on bottom most level only, which saves CPU
- Use binary search index which saves space compared to hash index
- Optimize level compaction for lower write amplification by growing levels faster
- Remove LHS_X_ROCKSDB_USE_LEVEL_COMPACTION and make it always true
- Remove LHS_TIMER_MEMTABLE_SIZE_BYTES in favor of using the same size with core
- Sets rocksdb block size to 64KB
> perf(server): optimize rocksdb compaction configs

- .github/workflows/branch.yml
- .github/workflows/publish-docker.yml
- docker/canary/Dockerfile
- docker/canary/docker-entrypoint.sh
- docker/standalone/Dockerfile
- docker/standalone/littlehorse-entrypoint.sh
- local-dev/build.sh
ShadowJar is broken since the Java upgrade. This makes the standalone image to use the built binary.
> fix(standalone): use server dist binary
